//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefenderCharacteristics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefenderCharacteristics()
        {
            this.PlayerToDFCharacteristics = new HashSet<PlayerToDFCharacteristics>();
        }
    
        public int IdDFChar { get; set; }
        public byte DribblingDF { get; set; }
        public byte HeadingDF { get; set; }
        public byte LongShotsDF { get; set; }
        public byte MarkingDF { get; set; }
        public byte PassingDF { get; set; }
        public byte TacklingDF { get; set; }
        public byte CrossingDF { get; set; }
        public byte WorkRateDF { get; set; }
        public byte BraveryDF { get; set; }
        public byte ConcentrationDF { get; set; }
        public byte HeightDF { get; set; }
        public byte WeightDF { get; set; }
        public byte LeadershipDF { get; set; }
        public byte StaminaDF { get; set; }
        public byte JumpingDF { get; set; }
        public byte StrengthDF { get; set; }
        public byte PositioningDF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToDFCharacteristics> PlayerToDFCharacteristics { get; set; }
    }
}
