//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseToTraining
    {
        public int IdExeToTra { get; set; }
        public int IdTraining { get; set; }
        public int IdExercise { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Training Training { get; set; }
    }
}
