//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseForTest
    {
        public int IdExerciseForTest { get; set; }
        public int IdPlayer { get; set; }
        public int IdExercise { get; set; }
        public string Time { get; set; }
        public string Number { get; set; }
        public System.DateTime DateTesting { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Player Player { get; set; }
    }
}
