//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwardCharacteristics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForwardCharacteristics()
        {
            this.PlayerToFWCharacteristics = new HashSet<PlayerToFWCharacteristics>();
        }
    
        public int IdFWChar { get; set; }
        public byte DribblingFW { get; set; }
        public byte PaceFW { get; set; }
        public byte LongShotsFW { get; set; }
        public byte PenaltyFW { get; set; }
        public byte PassingFW { get; set; }
        public byte HeadingFW { get; set; }
        public byte AgilityFW { get; set; }
        public byte FinishingFW { get; set; }
        public byte FitnessFW { get; set; }
        public byte JumpingFW { get; set; }
        public byte HeightFW { get; set; }
        public byte WeightFW { get; set; }
        public byte LeadershipFW { get; set; }
        public byte StaminaFW { get; set; }
        public byte AccelerationFW { get; set; }
        public byte StrengthFW { get; set; }
        public byte TechniqueFW { get; set; }
        public byte TeamWorkFW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToFWCharacteristics> PlayerToFWCharacteristics { get; set; }
    }
}
