//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalKeeperCharacteristics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoalKeeperCharacteristics()
        {
            this.PlayerToGKCharacteristics = new HashSet<PlayerToGKCharacteristics>();
        }
    
        public int IdGKChar { get; set; }
        public byte AgilityGK { get; set; }
        public byte JumpingGK { get; set; }
        public byte HeightGK { get; set; }
        public byte WeightGK { get; set; }
        public byte PenaltyTakingGK { get; set; }
        public byte VisionGK { get; set; }
        public byte AnticipationGK { get; set; }
        public byte DecisionsGK { get; set; }
        public byte LeadershipGK { get; set; }
        public byte PositioningGK { get; set; }
        public byte ThrowingGK { get; set; }
        public byte KickingGK { get; set; }
        public byte CommunicationGK { get; set; }
        public byte OneOnOnesGK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToGKCharacteristics> PlayerToGKCharacteristics { get; set; }
    }
}
