//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfChangingSkills
    {
        public int IdAction { get; set; }
        public string Action { get; set; }
        public Nullable<int> IdPlayer { get; set; }
        public System.DateTime TimeOfChange { get; set; }
        public Nullable<byte> PreviousValue { get; set; }
        public Nullable<byte> NewValue { get; set; }
        public Nullable<short> Difference { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
