//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InjuryToPlayer
    {
        public int IdInjToPla { get; set; }
        public int IdPlayer { get; set; }
        public int IdInjury { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOfInjury { get; set; }
        public Nullable<System.DateTime> DateOfRecovery { get; set; }
        public string Treatment { get; set; }
    
        public virtual Injury Injury { get; set; }
        public virtual Player Player { get; set; }
    }
}
