//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageToPlayer
    {
        public int IdPlaToLang { get; set; }
        public int IdPlayer { get; set; }
        public byte IdLanguage { get; set; }
        public Nullable<byte> IdStatusOfLanguage { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual Player Player { get; set; }
        public virtual StatusOfLanguage StatusOfLanguage { get; set; }
    }
}
