//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerToPosition
    {
        public int IdPlaToPos { get; set; }
        public int IdPlayer { get; set; }
        public byte IdPosition { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Position Position { get; set; }
    }
}
