//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.ExerciseForTest = new HashSet<ExerciseForTest>();
            this.HistoryOfChangingSkills = new HashSet<HistoryOfChangingSkills>();
            this.IndividualTraining = new HashSet<IndividualTraining>();
            this.InjuryToPlayer = new HashSet<InjuryToPlayer>();
            this.LanguageToPlayer = new HashSet<LanguageToPlayer>();
            this.NationalityToPlayer = new HashSet<NationalityToPlayer>();
            this.PlayerToMFCharacteristics = new HashSet<PlayerToMFCharacteristics>();
            this.PlayerToDFCharacteristics = new HashSet<PlayerToDFCharacteristics>();
            this.PlayerToFWCharacteristics = new HashSet<PlayerToFWCharacteristics>();
            this.PlayerToGKCharacteristics = new HashSet<PlayerToGKCharacteristics>();
            this.PlayerToPosition = new HashSet<PlayerToPosition>();
            this.PlayerToRespReson = new HashSet<PlayerToRespReson>();
            this.PlayerToTraits = new HashSet<PlayerToTraits>();
            this.PredispositionToPlayer = new HashSet<PredispositionToPlayer>();
            this.Reprimand = new HashSet<Reprimand>();
        }
    
        public int IdPlayer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte IdRole { get; set; }
        public Nullable<byte> IdDominantLeg { get; set; }
        public byte[] PlayerImage { get; set; }
        public byte idGender { get; set; }
        public Nullable<System.DateTime> DateJoining { get; set; }
    
        public virtual DominantLeg DominantLeg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExerciseForTest> ExerciseForTest { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfChangingSkills> HistoryOfChangingSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualTraining> IndividualTraining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuryToPlayer> InjuryToPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageToPlayer> LanguageToPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NationalityToPlayer> NationalityToPlayer { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToMFCharacteristics> PlayerToMFCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToDFCharacteristics> PlayerToDFCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToFWCharacteristics> PlayerToFWCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToGKCharacteristics> PlayerToGKCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToPosition> PlayerToPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToRespReson> PlayerToRespReson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerToTraits> PlayerToTraits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PredispositionToPlayer> PredispositionToPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reprimand> Reprimand { get; set; }
    }
}
