//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerToDisadvantages
    {
        public int IdPlToDis { get; set; }
        public int IdPlayer { get; set; }
        public int IdDisAdv { get; set; }
        public Nullable<byte> IdStatus { get; set; }
    
        public virtual Disadvantages Disadvantages { get; set; }
        public virtual Player Player { get; set; }
        public virtual StatusOfDisadvantage StatusOfDisadvantage { get; set; }
    }
}
