//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerToGKCharacteristics
    {
        public int IdPlaToGK { get; set; }
        public int IdPlayer { get; set; }
        public int IdGKChar { get; set; }
    
        public virtual GoalKeeperCharacteristics GoalKeeperCharacteristics { get; set; }
        public virtual Player Player { get; set; }
    }
}
