//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reprimand
    {
        public int IdPlaToRep { get; set; }
        public string ReprimandName { get; set; }
        public int IdPlayer { get; set; }
        public byte IdPunishment { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Punishment Punishment { get; set; }
    }
}
