//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInfoTournament
    {
        public int IdTournament { get; set; }
        public string TournamentName { get; set; }
        public string PrizePool { get; set; }
        public Nullable<byte> NumberOfParticipants { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string City { get; set; }
        public string CountryName { get; set; }
        public string SponsorName { get; set; }
        public Nullable<int> IdCountry { get; set; }
    }
}
