//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTeamTrainings
    {
        public string ClubName { get; set; }
        public string TrainingName { get; set; }
        public System.DateTime Date { get; set; }
        public int IdTraining { get; set; }
        public int IdTeam { get; set; }
        public int IdTTT { get; set; }
    }
}
