//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShowPositions
    {
        public string Fullname { get; set; }
        public string DominantLeg { get; set; }
        public string Positions { get; set; }
        public byte[] PlayerImage { get; set; }
        public int IdPlayer { get; set; }
    }
}
