//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPredispositions
    {
        public string Fullname { get; set; }
        public Nullable<byte> Age { get; set; }
        public string NameGender { get; set; }
        public string PredispositionName { get; set; }
        public string Description { get; set; }
        public string Treatment { get; set; }
    }
}
