//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTeamTrainings
    {
        public string ClubName { get; set; }
        public string TrainingName { get; set; }
        public System.DateTime Date { get; set; }
        public string CountryName { get; set; }
        public string City { get; set; }
        public string Manager_s_Name { get; set; }
    }
}
