//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGkCharacteristics
    {
        public string FullName { get; set; }
        public byte AgilityGK { get; set; }
        public byte JumpingGK { get; set; }
        public byte HeightGK { get; set; }
        public byte WeightGK { get; set; }
        public byte PenaltyTakingGK { get; set; }
        public byte VisionGK { get; set; }
        public byte AnticipationGK { get; set; }
        public byte DecisionsGK { get; set; }
        public byte LeadershipGK { get; set; }
        public byte PositioningGK { get; set; }
        public byte ThrowingGK { get; set; }
        public byte KickingGK { get; set; }
        public byte CommunicationGK { get; set; }
        public byte OneOnOnesGK { get; set; }
        public int IdPlaToGK { get; set; }
        public int IdPlayer { get; set; }
        public int IdGKChar { get; set; }
    }
}
