//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewResponsiblePerson
    {
        public string Player { get; set; }
        public string Player_s_Phone { get; set; }
        public string Player_s_Email { get; set; }
        public string Pesponsible_Person { get; set; }
        public string Resp_Person_s_phone { get; set; }
        public string NameGender { get; set; }
        public Nullable<int> IdRespPerson { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string MiddleName2 { get; set; }
        public Nullable<int> IdPlayer { get; set; }
    }
}
