//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllInfo
    {
        public string FullName { get; set; }
        public Nullable<byte> Age { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte[] PlayerImage { get; set; }
        public Nullable<System.DateTime> DateJoining { get; set; }
        public string NameGender { get; set; }
        public string Languages { get; set; }
        public string Citizenships { get; set; }
    }
}
