//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootDev2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllInfo
    {
        public string FullName { get; set; }
        public Nullable<byte> Age { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] PlayerImage { get; set; }
        public Nullable<System.DateTime> DateJoining { get; set; }
        public string NameGender { get; set; }
        public string Languages { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Password { get; set; }
        public byte IdDominantLeg { get; set; }
        public string Name { get; set; }
        public string NationalityName { get; set; }
        public byte idGender { get; set; }
        public int IdNationality { get; set; }
        public int IdPlayer { get; set; }
    }
}
